### ISSUE TITLE
PNG Repacking

### ISSUE THREAD

**Issue by SillyconWilly** [sam-k0/YYC_ripper#2]
Hi!

Your little tool is great. It found and extracted that image file I needed to edit. But now I have to insert it back. Do you maybe have created or know a similar tool that repacks the edited image file? That would then be even greater than great. ;-)

bye

**Comment by sam-k0** [comment]
Sadly I don't have a tool that does this, but:
there is UndertaleModTool which as far as I know can do that.

Short explanation is, I didn't get around to repackage the changed spritesheet back into the game bundle as it's a bit complicated. 
Essentially when you change a single pixel / color, the size of the spritesheet may change, and so would the offsets for the bytecode. Also, the way assets are stored (probably) changed from gamemaker version 1.4 to 2 and 2.3 which makes it even harder.

**Comment by SillyconWilly** [comment]
Hi!
Thank you for your reply. Sadly to hear this but I'm gonna download the UndertaleModTool and give it a try. Thank you for that recommendation.
And about the other. Yes I know that problem. I already edited images and the size changed. Because of that change some other values change too and the reinserting fails. Usually I use "usenti" for png or bmp editing. It's a little fine tool for pixel work. And the problem with app updates I know from the work with the "famous-notorious" cheat engine. :-) Sometimes I cheat in games and so I know that every update can change the addresses. Resulting in useless cheat codes. :-( But thank you for your note. :-) Have a good time.

bye

    Am Sonntag, 4. August 2024 um 20:51:32 MESZ hat sam-k0 ***@***.***> Folgendes geschrieben:   

 


Sadly I don't have a tool that does this, but:
there is UndertaleModTool which as far as I know can do that.

Short explanation is, I didn't get around to repackage the changed spritesheet back into the game bundle as it's a bit complicated.
Essentially when you change a single pixel / color, the size of the spritesheet may change, and so would the offsets for the bytecode. Also, the way assets are stored (probably) changed from gamemaker version 1.4 to 2 and 2.3 which makes it even harder.
